interface TermsOfServiceProps {
  onClose: () => void;
}

export function TermsOfService({ onClose }: TermsOfServiceProps) {
  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/50">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full max-h-[80vh] overflow-y-auto p-8">
        <h2 className="text-2xl font-serif text-gray-800 mb-1">Terms of Service</h2>
        <p className="text-sm text-gray-400 mb-6">Effective Date: April 9, 2026</p>

        <div className="space-y-5 text-gray-600 text-sm leading-relaxed">

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">1. Acceptance of Terms</h3>
            <p>By accessing or using the Digital Dog Day Planner &amp; Calendar ("the App"), you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use the App.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">2. Description of Service</h3>
            <p>The Digital Dog Day Planner &amp; Calendar is a free web-based application that allows registered users to plan and track activities for their dogs, access breed information, use an AI-powered planning assistant, and sync events with external calendar services.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">3. User Accounts</h3>
            <p>You must provide a valid email address to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to notify us immediately of any unauthorized use of your account.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">4. Acceptable Use</h3>
            <p>You agree to use the App only for lawful purposes and in accordance with these Terms. You agree not to:</p>
            <ul className="list-disc ml-5 mt-1 space-y-1">
              <li>Use the App in any way that violates applicable laws or regulations</li>
              <li>Attempt to gain unauthorized access to any part of the App or its infrastructure</li>
              <li>Transmit harmful, offensive, or disruptive content through the App</li>
              <li>Use automated tools to scrape or extract data from the App</li>
            </ul>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">5. AI Assistant</h3>
            <p>The App includes an AI-powered planning assistant. The responses generated by the AI are for informational and planning purposes only and do not constitute professional veterinary, medical, or legal advice. Always consult a qualified veterinarian for health concerns about your pet.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">6. Third-Party Integrations</h3>
            <p>The App may integrate with third-party services including Google Calendar and Outlook. Your use of those services is subject to their respective terms of service and privacy policies. We are not responsible for the practices of third-party services.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">7. Intellectual Property</h3>
            <p>All content, design, graphics, and software included in the App are the property of Digital Dog Day Planner &amp; Calendar and are protected by applicable copyright and intellectual property laws. You may not reproduce, distribute, or create derivative works without prior written permission.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">8. Disclaimer of Warranties</h3>
            <p>The App is provided "as is" and "as available" without warranties of any kind, either express or implied. We do not warrant that the App will be uninterrupted, error-free, or free of viruses or other harmful components.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">9. Limitation of Liability</h3>
            <p>To the fullest extent permitted by law, Digital Dog Day Planner &amp; Calendar shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of or inability to use the App.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">10. Changes to Terms</h3>
            <p>We reserve the right to modify these Terms at any time. Continued use of the App after changes are posted constitutes your acceptance of the revised Terms.</p>
          </section>

          <section>
            <h3 className="font-semibold text-gray-800 mb-1">11. Contact</h3>
            <p>For questions about these Terms, please contact us through the App's feedback feature.</p>
          </section>

          <p className="text-xs text-gray-400 pt-2">© 2026 Digital Dog Day Planner &amp; Calendar. All Rights Reserved.</p>
        </div>

        <button onClick={onClose} className="mt-6 px-6 py-2 bg-amber-600 text-white rounded-lg hover:bg-amber-700 transition-colors">Close</button>
      </div>
    </div>
  );
}
