/* AUTOGENERATED FILE - edited 2026-09-24, see note below */
export const projectId = "zkdqvxaihllzqtnuejqa"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InprZHF2eGFpaGxsenF0bnVlanFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYwNjkwNjMsImV4cCI6MjA4MTY0NTA2M30.T_SA17QrITykMi4uKSEnLFXdEZ572rM8ghDFEM-T1BA"

// This file used to call createClient() itself, producing a SECOND Supabase
// client with no session. AuthForm/App sign in against src/app/lib/supabase.ts,
// so any component importing `supabase` from here talked to the database as an
// anonymous visitor - which is why RLS policies scoped to the signed-in user
// returned 401 and why the old policies had to be USING (true) to work at all.
// Re-export the real singleton instead so there is exactly one client.
export { supabase } from "../../src/app/lib/supabase";
