-- ============================================================================
-- BASELINE - existing schema back-filled 2026-09-23
--
-- ⚠️ THIS IS A RECONSTRUCTION, NOT A DUMP. READ BEFORE TRUSTING IT.
-- ⚠️ IT IS ALSO INCOMPLETE - IT COVERS 3 OF THE PROJECT'S 10 TABLES.
--
-- These tables were created by hand in the Supabase dashboard long before any
-- migration existed. This file reconstructs them so `supabase db reset` and
-- preview branches can build the schema, and so new environments get the GRANTs
-- that Supabase stops issuing automatically on 2026-10-30.
--
-- INCOMPLETE: the dashboard shows TEN tables in `public` on 2026-09-23, all of
-- them flagged as exposed through the Data API:
--     activities, appointments, calendar_events, dogs, events, feedback,
--     hourly_plans, kv_store_7edd5186, schedules, user_calendar_tokens
-- Only feedback, hourly_plans and kv_store_7edd5186 are reconstructed below -
-- they are the only three referenced anywhere in the application source, so
-- they are the only three whose shape could be derived. The other seven are
-- NOT in this file and a fresh environment built from these migrations will
-- NOT have them. Run `supabase db pull` to capture the real thing.
--
-- ⚠️ user_calendar_tokens almost certainly holds Google OAuth access/refresh
-- tokens (the project has GOOGLE_CLIENT_ID / SECRET / REDIRECT_URI in .env.dog
-- and Calendar sync is a premium feature). Its RLS and anon grants should be
-- audited FIRST - a readable token table is far worse than readable planner
-- rows. Not inspected as of 2026-09-23.
--
-- Source of each part:
--   kv_store_7edd5186 - EXACT. Verbatim DDL from the autogenerated comment in
--                       supabase/functions/make-server-7edd5186/kv_store.tsx.
--   hourly_plans      - COLUMNS + TYPES ARE REAL, observed from a live row via
--                       the REST API on 2026-09-23. Constraints, defaults,
--                       indexes and identity settings are INFERRED.
--   feedback          - INFERRED from the insert at index.ts:437 only
--                       ({ email, message }). Least reliable of the three.
--
-- Timestamped 2026-01-01 so it sorts BEFORE 20260923120000_monetization.sql.
--
-- TO REPLACE THIS WITH THE AUTHORITATIVE SCHEMA:
--   npx supabase login          <- needs a browser; CLI is not authenticated
--   npx supabase link --project-ref zkdqvxaihllzqtnuejqa
--   npx supabase db pull
-- That writes a true dump. Delete this file if the dump supersedes it.
--
-- DO NOT run this against the live project - the tables already exist there.
-- It is for fresh environments (db reset / preview branches / a new project).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- kv_store_7edd5186  (EXACT - Figma Make key-value store, service_role only)
-- ---------------------------------------------------------------------------
create table if not exists public.kv_store_7edd5186 (
  key   text not null primary key,
  value jsonb not null
);

-- ---------------------------------------------------------------------------
-- hourly_plans  (columns/types REAL; constraints INFERRED)
--
-- Observed live row:
--   {"id":1,"email":"...","year":2026,"month":3,"day":27,"hour":9,
--    "plan":"Team meeting with project updates",
--    "created_at":"2026-03-27T18:13:23.055021+00:00",
--    "updated_at":"2026-03-27T18:13:22.898+00:00"}
--
-- The app filters on (email, year, month) and inserts (email, year, month,
-- day, hour, plan) - see DayModal.tsx:133/247/262/270 and CalendarGrid.tsx:33.
-- INFERRED: that (email, year, month, day, hour) is meant to be unique. The app
-- DELETEs then INSERTs rather than upserting, so no unique constraint may
-- actually exist today. Verify before relying on it.
-- ---------------------------------------------------------------------------
create table if not exists public.hourly_plans (
  id         bigint generated by default as identity primary key,
  email      text not null,
  year       integer not null,
  month      integer not null,
  day        integer not null,
  hour       integer not null,
  plan       text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists hourly_plans_lookup_idx
  on public.hourly_plans (email, year, month);

-- ---------------------------------------------------------------------------
-- feedback  (INFERRED - only { email, message } are confirmed, from index.ts)
-- ---------------------------------------------------------------------------
create table if not exists public.feedback (
  id         bigint generated by default as identity primary key,
  email      text,
  message    text not null,
  created_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- GRANTS - required for any table created from 2026-10-30 onward
--
-- These mirror how each table is ACTUALLY reached today:
--   hourly_plans      - the browser client, anon key (utils/supabase/info.tsx)
--   kv_store_7edd5186 - edge function only, service_role
--   feedback          - edge function only, service_role
-- ---------------------------------------------------------------------------

grant select, insert, update, delete on public.hourly_plans to anon, authenticated;
grant select, insert, update, delete on public.hourly_plans to service_role;

grant select, insert, update, delete on public.kv_store_7edd5186 to service_role;

grant select, insert, update, delete on public.feedback to service_role;

-- ---------------------------------------------------------------------------
-- ⚠️ RLS IS DELIBERATELY NOT SET HERE - AND THAT IS A PROBLEM TO FIX.
--
-- On 2026-09-23 a plain REST GET on hourly_plans using the PUBLIC ANON KEY
-- returned a full row, including the account email and the plan text. The anon
-- key ships inside the frontend bundle, so it is public by design. That means
-- planner content is readable by anyone who reads the shipped JS - unless an
-- RLS policy that was not exercised by that request is restricting it.
--
-- This file does NOT enable RLS, because switching it on blind would instantly
-- break the live app: hourly_plans is keyed by `email` (text), not by
-- auth.uid(), so there is no policy that both secures it and keeps the current
-- queries working. Fixing it properly means migrating the table to user_id, or
-- adding a policy that matches auth.jwt() ->> 'email' against the email column.
--
-- TRACKED, NOT FIXED. Decide the approach before writing that migration.
-- ---------------------------------------------------------------------------
